package numberPlay.util;

import numberPlay.observer.RunningAverageObserver;

/**
* RunningAverageResultsI defines an interface to be implemented by
* classes that intend to stroe the running average for each number
* processed in a stream of numbers.
*/
public interface RunningAverageResultsI {
	
	/**
	 * Method to store running average result generated by {@code RunningAverageObserver}
	 * @param d calculated Average value
	 */
	void store(Double d);
}
