package numberPlay.util;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import numberPlay.observer.TopKNumberObserver;

/**
 * The class {@code TopKNumbersData} is used to store the result generated by {@code TopKNumberObserver} and writes that result into output file
 * @author Sagar Toke 
 *
 */
public class TopKNumbersData implements PersisterI, TopKNumbersResultsI {
	private String topKNumberOutputFile;
	private static StringBuilder topKList = new StringBuilder();
	private OutputStreamWriter outputFileWriter;
	private File outputFile;

	public TopKNumbersData() {
		// TODO Auto-generated constructor stub
	}

	public TopKNumbersData(String topKNumberOutputFileIn) {
		topKNumberOutputFile = topKNumberOutputFileIn;
	}

	@Override
	public void store(List<Double> topK) {
		topKList.append(topK + "\n");
		// topK.addAll(topK);

	}

	@Override
	public void writeToFile() {
		try {
			if (!Files.exists(Paths.get(topKNumberOutputFile))) {
				outputFile = new File(topKNumberOutputFile);
				outputFile.createNewFile();
				outputFileWriter = new FileWriter(topKNumberOutputFile);
				outputFileWriter.write(topKList.toString());
			} else {
				outputFileWriter = new FileWriter(topKNumberOutputFile);

				outputFileWriter.write(topKList.toString());
			}
		} catch (IOException e) {
			e.printStackTrace();
		}

	}

	@Override
	public void close() {

		try {
			outputFileWriter.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
